In [1]:
import pandas as pd
import json

In [11]:
#PRIMER DATASET
EloRatings = pd.read_csv("../csv/EventosDeportivos/EloRatings.csv")

In [12]:
#SEGUNDO DATASET
EventosAtleticos = pd.read_csv("../csv/EventosDeportivos/athleticEvents.csv")

In [27]:
EventosAtleticos

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271111,135569,Andrzej ya,M,29.0,179.0,89.0,Poland-1,POL,1976 Winter,1976,Winter,Innsbruck,Luge,Luge Mixed (Men)'s Doubles,NaN
271112,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014 Winter,2014,Winter,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Individual",NaN
271113,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014 Winter,2014,Winter,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Team",NaN
271114,135571,Tomasz Ireneusz ya,M,30.0,185.0,96.0,Poland,POL,1998 Winter,1998,Winter,Nagano,Bobsleigh,Bobsleigh Men's Four,NaN
271115,135571,Tomasz Ireneusz ya,M,34.0,185.0,96.0,Poland,POL,2002 Winter,2002,Winter,Salt Lake City,Bobsleigh,Bobsleigh Men's Four,NaN

In [13]:
#TERCER DATASET
WordCup = pd.read_csv("../csv/EventosDeportivos/WorldCups.csv")

In [26]:
WordCup

   Year;Country;Winner;Runners-Up;Third;Fourth;GoalsScored;QualifiedTeams;MatchesPlayed;Attendance
0   1930;Uruguay;Uruguay;Argentina;USA;Yugoslavia;...
1   1934;Italy;Italy;Czechoslovakia;Germany;Austri...
2   1938;France;Italy;Hungary;Brazil;Sweden;84;15;...
3   1950;Brazil;Uruguay;Brazil;Sweden;Spain;88;13;...
4   1954;Switzerland;Germany FR;Hungary;Austria;Ur...
5   1958;Sweden;Brazil;Sweden;France;Germany FR;12...
6   1962;Chile;Brazil;Czechoslovakia;Chile;Yugosla...
7   1966;England;England;Germany FR;Portugal;Sovie...
8   1970;Mexico;Brazil;Italy;Germany FR;Uruguay;95...
9   1974;Germany;Germany FR;Netherlands;Poland;Bra...
10  1978;Argentina;Argentina;Netherlands;Brazil;It...
11  1982;Spain;Italy;Germany FR;Poland;France;146;...
12  1986;Mexico;Argentina;Germany FR;France;Belgiu...
13  1990;Italy;Germany FR;Argentina;Italy;England;...
14  1994;USA;Brazil;Italy;Sweden;Bulgaria;141;24;5...
15  1998;France;France;Brazil;Croatia;Netherlands;...
16  2002;Korea/Japan;Brazil;Germany;Turkey;Korea R...
17  2006;Germany;Italy;France;Germany;Portugal;147...
18  2010;South Africa;Spain;Netherlands;Germany;Ur...
19  2014;Brazil;Germany;Argentina;Netherlands;Braz...
20  2018;Russia;France;Croatia;Belgium;England;169...
21  2022;Qatar;Argentina;France;Croatia;Morocco;17...

In [25]:
#CUARTO DATASET
WordCupMatches = pd.read_csv("../csv/EventosDeportivos/WorldCupMatch.csv")

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x95 in position 7811: invalid start byte

In [8]:
EloRatingsJS = EloRatings.to_dict(orient="records")

In [10]:
with open("../json/EventosDeportivos/EloRatings.json", "w", encoding="utf-8") as json_file:
    json.dump(EloRatingsJS, json_file, indent=4, ensure_ascii=False)